---
apiVersion: v1
offerings:
  - name: testing-deploy-arch-ibm-scc
    kind: solution
    catalog_id: f64499c8-eb50-4985-bf91-29f9e605a433
    offering_id: b773b1d4-69bb-48db-a657-2307015eb9c1
    variations:
      - name: instances
        mark_ready: true
        install_type: fullstack
        scc:
          instance_id: 1c7d5f78-9262-44c3-b779-b28fe4d88c37
          region: us-south
